# GLAD loader for OpenGL
#
# Generator: https://glad.dav1d.de/
# Configuration: GL 3.3, Core Profile

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "glad",
    strip_include_prefix = "include",
    hdrs = [ "include/glad/glad.h" ],
    srcs = [ "src/glad.c" ],
)
